### ISSUE TITLE
Slim Build - json.stringify is not a function (lowercase issue)

### ISSUE THREAD

**Issue by gierschv** [socketio/socket.io-client#1034]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

```
Uncaught TypeError: json.stringify is not a function
```

### Steps to reproduce (if the current behaviour is a bug)

Using the new slim build in 1.7

### Expected behaviour

The code should use [JSON.stringify](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify), not `json.stringify`.
