### ISSUE TITLE
Problem with karma typescript

### ISSUE THREAD

**Issue by xgrommx** [socketio/socket.io-client#1426]
Hello everyone. After update to 3 version I got several errors

```
node_modules/socket.io-client/build/socket.d.ts(38,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/socket.io-client/build/socket.d.ts(168,9): error TS1086: An accessor cannot be declared in an ambient context.
```

How can I fix it?

**Comment by darrachequesne** [comment]
Hi! Which version of typescript are you using? I can't reproduce with the example here: https://github.com/socketio/socket.io/tree/master/examples/typescript

(tested with typescript `4.0.5` and `3.6.5`)

**Comment by MaximeMnt** [comment]
Same issue here, i'm building an Angular app. 
`Angular CLI: 10.1.7
Node: 12.19.0
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1001.7 (cli-only)
@angular-devkit/core         10.1.7 (cli-only)
@angular-devkit/schematics   10.1.7 (cli-only)
@schematics/angular          10.1.7 (cli-only)
@schematics/update           0.1001.7 (cli-only)`

**Comment by MaximeMnt** [comment]
I found a possible solution, Adding this line into the ```tsconfig.json``` file fixed the error! 
````"compilerOptions": {
    "skipLibCheck": true
}```

**Comment by darrachequesne** [comment]
It seems to be linked to the issue here: https://github.com/microsoft/TypeScript/issues/33939

I'm not sure if we can do something about it though...
